//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from php.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


    using System;
    using System.Text;
    using System.Collections.Generic;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="phpParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IphpListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.phpDoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPhpDoc([NotNull] phpParser.PhpDocContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.phpDoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPhpDoc([NotNull] phpParser.PhpDocContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] phpParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] phpParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.varDump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDump([NotNull] phpParser.VarDumpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.varDump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDump([NotNull] phpParser.VarDumpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.varDumpArgHelp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDumpArgHelp([NotNull] phpParser.VarDumpArgHelpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.varDumpArgHelp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDumpArgHelp([NotNull] phpParser.VarDumpArgHelpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.varDumpArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDumpArg([NotNull] phpParser.VarDumpArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.varDumpArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDumpArg([NotNull] phpParser.VarDumpArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.echoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEchoStatement([NotNull] phpParser.EchoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.echoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEchoStatement([NotNull] phpParser.EchoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.echoArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEchoArgument([NotNull] phpParser.EchoArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.echoArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEchoArgument([NotNull] phpParser.EchoArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] phpParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] phpParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] phpParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] phpParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] phpParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] phpParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarName([NotNull] phpParser.VarNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarName([NotNull] phpParser.VarNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.functionDec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDec([NotNull] phpParser.FunctionDecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.functionDec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDec([NotNull] phpParser.FunctionDecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] phpParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] phpParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.parameterVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterVar([NotNull] phpParser.ParameterVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.parameterVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterVar([NotNull] phpParser.ParameterVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionBody([NotNull] phpParser.FunctionBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionBody([NotNull] phpParser.FunctionBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.functionBodystatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionBodystatements([NotNull] phpParser.FunctionBodystatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.functionBodystatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionBodystatements([NotNull] phpParser.FunctionBodystatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] phpParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] phpParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionName([NotNull] phpParser.FunctionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionName([NotNull] phpParser.FunctionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] phpParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] phpParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] phpParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] phpParser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] phpParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] phpParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.ifStatemetDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatemetDefault([NotNull] phpParser.IfStatemetDefaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.ifStatemetDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatemetDefault([NotNull] phpParser.IfStatemetDefaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.elseifDefaultStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseifDefaultStatement([NotNull] phpParser.ElseifDefaultStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.elseifDefaultStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseifDefaultStatement([NotNull] phpParser.ElseifDefaultStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.elseDefaultStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseDefaultStatement([NotNull] phpParser.ElseDefaultStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.elseDefaultStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseDefaultStatement([NotNull] phpParser.ElseDefaultStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.ifStatementAlternate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatementAlternate([NotNull] phpParser.IfStatementAlternateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.ifStatementAlternate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatementAlternate([NotNull] phpParser.IfStatementAlternateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.elseifAlternateStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseifAlternateStatement([NotNull] phpParser.ElseifAlternateStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.elseifAlternateStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseifAlternateStatement([NotNull] phpParser.ElseifAlternateStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.elseAlternateStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseAlternateStatement([NotNull] phpParser.ElseAlternateStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.elseAlternateStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseAlternateStatement([NotNull] phpParser.ElseAlternateStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.conditionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionBody([NotNull] phpParser.ConditionBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.conditionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionBody([NotNull] phpParser.ConditionBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] phpParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] phpParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.parenthesis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesis([NotNull] phpParser.ParenthesisContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.parenthesis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesis([NotNull] phpParser.ParenthesisContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] phpParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] phpParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.comparision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparision([NotNull] phpParser.ComparisionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.comparision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparision([NotNull] phpParser.ComparisionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd([NotNull] phpParser.AddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd([NotNull] phpParser.AddContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMult([NotNull] phpParser.MultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMult([NotNull] phpParser.MultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.nLRE"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNLRE([NotNull] phpParser.NLREContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.nLRE"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNLRE([NotNull] phpParser.NLREContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.switchStatementDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatementDefault([NotNull] phpParser.SwitchStatementDefaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.switchStatementDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatementDefault([NotNull] phpParser.SwitchStatementDefaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.switchStatementAlternate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatementAlternate([NotNull] phpParser.SwitchStatementAlternateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.switchStatementAlternate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatementAlternate([NotNull] phpParser.SwitchStatementAlternateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.switchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchBlock([NotNull] phpParser.SwitchBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.switchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchBlock([NotNull] phpParser.SwitchBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.switchCases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchCases([NotNull] phpParser.SwitchCasesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.switchCases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchCases([NotNull] phpParser.SwitchCasesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.switchCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchCase([NotNull] phpParser.SwitchCaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.switchCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchCase([NotNull] phpParser.SwitchCaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.addAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddAction([NotNull] phpParser.AddActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.addAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddAction([NotNull] phpParser.AddActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.multAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultAction([NotNull] phpParser.MultActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.multAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultAction([NotNull] phpParser.MultActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAction([NotNull] phpParser.ActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAction([NotNull] phpParser.ActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="phpParser.compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompare([NotNull] phpParser.CompareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="phpParser.compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompare([NotNull] phpParser.CompareContext context);
}
