//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from php.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


    using System;
    using System.Text;
    using System.Collections.Generic;

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="phpParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IphpVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.phpDoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhpDoc([NotNull] phpParser.PhpDocContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] phpParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.varDump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDump([NotNull] phpParser.VarDumpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.varDumpArgHelp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDumpArgHelp([NotNull] phpParser.VarDumpArgHelpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.varDumpArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDumpArg([NotNull] phpParser.VarDumpArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.echoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEchoStatement([NotNull] phpParser.EchoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.echoArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEchoArgument([NotNull] phpParser.EchoArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] phpParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] phpParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] phpParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarName([NotNull] phpParser.VarNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.functionDec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDec([NotNull] phpParser.FunctionDecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] phpParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.parameterVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterVar([NotNull] phpParser.ParameterVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionBody([NotNull] phpParser.FunctionBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.functionBodystatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionBodystatements([NotNull] phpParser.FunctionBodystatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] phpParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionName([NotNull] phpParser.FunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] phpParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] phpParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] phpParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.ifStatemetDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatemetDefault([NotNull] phpParser.IfStatemetDefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.elseifDefaultStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseifDefaultStatement([NotNull] phpParser.ElseifDefaultStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.elseDefaultStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseDefaultStatement([NotNull] phpParser.ElseDefaultStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.ifStatementAlternate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatementAlternate([NotNull] phpParser.IfStatementAlternateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.elseifAlternateStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseifAlternateStatement([NotNull] phpParser.ElseifAlternateStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.elseAlternateStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseAlternateStatement([NotNull] phpParser.ElseAlternateStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.conditionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionBody([NotNull] phpParser.ConditionBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] phpParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.parenthesis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesis([NotNull] phpParser.ParenthesisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] phpParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.comparision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparision([NotNull] phpParser.ComparisionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd([NotNull] phpParser.AddContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMult([NotNull] phpParser.MultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.nLRE"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNLRE([NotNull] phpParser.NLREContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.switchStatementDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatementDefault([NotNull] phpParser.SwitchStatementDefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.switchStatementAlternate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatementAlternate([NotNull] phpParser.SwitchStatementAlternateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.switchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchBlock([NotNull] phpParser.SwitchBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.switchCases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchCases([NotNull] phpParser.SwitchCasesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.switchCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchCase([NotNull] phpParser.SwitchCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.addAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddAction([NotNull] phpParser.AddActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.multAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultAction([NotNull] phpParser.MultActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] phpParser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="phpParser.compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare([NotNull] phpParser.CompareContext context);
}
